# Generated by Django 4.1.7 on 2023-03-02 23:12

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("receipts", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="receipt",
            old_name="vender",
            new_name="vendor",
        ),
    ]
